### ISSUE TITLE
espanso substitutions do not work in neovide

### ISSUE THREAD

**Issue by kekscode** [Kethku/neovide#2305]
**Describe the bug**
I use espanso and it works for e.g. `,a` => `ä` in this textbox, in wezterm+nvim and in any other UI application on MacOS, but not in neovide, where it produces a single whitespace character instead of the substitution.

**To Reproduce**

1. Setup espanso (config below) and check if substitutions work.
2. Open neovide and  check if espanso substitutions work there, too.

Espanso config:

```yaml
# espanso match file
# For a complete introduction, visit the official docs at: https://espanso.org/docs/
matches:
  # Umlauts
  - trigger: ",s"
    replace: "ß"
  - trigger: ",A"
    replace: "Ä"
  - trigger: ",O"
    replace: "Ö"
  - trigger: ",U"
    replace: "Ü"
  - trigger: ",a"
    replace: "ä"
  - trigger: ",o"
    replace: "ö"
  - trigger: ",u"
    replace: "ü"
  - trigger: ",e"
    replace: "€"
```

**Expected behavior**
`,a,u,o,s` should lead to `äüöß`  when typing in insert mode.

**Screenshots**
<img width="828" alt="image" src="https://github.com/neovide/neovide/assets/803252/5621338e-76c2-4243-a1d8-2096c28fec5f">

**Desktop (please complete the following information):**
 - OS: macOS sonoma 14.3 (23D56)
 - Neovide 0.12.1
 - Neovim NVIM v0.9.5 Build type: Release LuaJIT 2.1.1703358377

**Please run `neovide --log` and paste the contents of the `.log` file created in the current directory here:**
I think this is not necessary, but i'll be happy to  provide it if requested.

**Additional context**
Pretty sure this has to do with the way neovide captures character input and how espanso operates (replacing  characters). But i don't  know any detail.
