### ISSUE TITLE
Flatpak

### ISSUE THREAD

**Issue by deisi** [Kethku/neovide#634]
Hey guys,

I'd like to contribute a little to neovide. Are there objections against a flatpack package? I could start making a manifest and see how it goes.

**Comment by j4qfrost** [comment]
No one is going to say no to free work. Just make sure it's not a virus. Good luck.

**Comment by deisi** [comment]
:)

> No one is going to say no to free work.

I got used to ask beforehand. Better save then sorry. 

>  Just make sure it's not a virus.

I do my best ;)

**Comment by theduke** [comment]
I'd really appreciate a Flatpak app!

**Comment by deisi** [comment]
will take a couple of days but i already started. I'm not sure how I will deal with the release system of neovide. Worst case I build within the manifest file, but maybe I'm fine with the taged commits.

**Comment by j4qfrost** [comment]
@deisi What are you referring to when you say release system? Are you talking about the git workflow?

**Comment by deisi** [comment]
Well, currently version 0.5.0 is considered as the last release, but the last tagged version is 0.7.0. I'm not sure what version I should put in the manifest. For now I focus on getting something that works and don't care about how I will handle future updates too much. I know that the process can be automated quite nicely, but that is taking step 2 before I have taken step 1.

**Comment by j4qfrost** [comment]
Gotcha, @ me when you're ready and I can help you set up a workflow pipeline to do packaging via github.

**Comment by deisi** [comment]
merci :)

**Comment by deisi** [comment]
I got a prototype working. I based it off:
https://github.com/flathub/io.neovim.nvim/blob/baf02021ed4c4752a71b0fe7c0fc183bfdbb3c00/io.neovim.nvim.yaml

to get the nvim part done, but to me that manifest is plain horror. I will see if I can manage to base the nvim part off the upstream appdata file, so the building of nvim is left to the developers of nvim.

**Comment by deisi** [comment]
Okay, I could drastically simplify the manifest by just using the appimage of nvim instead of compiling it myself. Here is the manifest as I use it right now. It will need some cleanup and a little more love, but it works.


``` yaml
app-id: org.neovide.neovide
runtime: org.gnome.Platform
runtime-version: "3.36"
sdk: org.gnome.Sdk
command: neovide
finish-args: 
  - --socket=x11
  - --socket=wayland
  - --share=network
  - --filesystem=home
  - --device=dri
  - --socket=pulseaudio
modules:
  - name: nvim
    buildsystem: simple
    sources: 
      - type: file
        url: https://github.com/neovim/neovim/releases/download/nightly/nvim.appimage
        sha256: 1eea3d44f55bab0856d08737c0c50ead7645ae3afd6352a252bc403b9843ec95
    build-commands:
      - chmod +x nvim.appimage
      - ./nvim.appimage --appimage-extract
      - mv squashfs-root/usr/* /app/

  - name: Neovide
    buildsystem: simple
    sources:
      - type: file
        url: https://github.com/Kethku/neovide/releases/download/0.7.0/neovide
        sha256: 2a984740f31fd72f26c5ae56f0f9a8c0e1285c688875dbc403be2bf44c1f29c4
        x-checker-data:
          type: json
          utl: https://api.github.com/repos/Kethku/neovide/releases/latest 
          url-query: .assets[] | select(.name==neovide) | .browser_download_url
      - type: git
        url: https://github.com/Kethku/neovide.git
        commit: 4bd6579074e73dbb8ea8e3fde1f427af143d0b7a
        dest: .
      - type: file
        path: org.neovide.neovide.metainfo.xml
    build-commands:
      - sed -i 's/Icon=neovide/Icon=org.neovide.neovide/g' assets/neovide.desktop
      - install -Dm644 assets/neovide-16x16.png /app/share/icons/hicolor/16x16/apps/${FLATPAK_ID}.png
      - install -Dm644 assets/neovide-32x32.png /app/share/icons/hicolor/16x16/apps/${FLATPAK_ID}.png
      - install -Dm644 assets/neovide-48x48.png /app/share/icons/hicolor/16x16/apps/${FLATPAK_ID}.png
      - install -Dm644 assets/neovide-256x256.png /app/share/icons/hicolor/16x16/apps/${FLATPAK_ID}.png
      - install -Dm644 assets/neovide.desktop /app/share/applications/${FLATPAK_ID}.desktop
      - install -Dm644 org.neovide.neovide.metainfo.xml /app/share/metainfo/${FLATPAK_ID}.metainfo.xml
      - install -Dm755 neovide /app/bin/neovide

```
